[phases.setup]
nixPkgs = [
  "mesa",
  "zlib",
  "python3",
  "xorg.libX11",
  "xorg.libXext",
  "xorg.libXrender",
  "xorg.libXrandr",
  "libglvnd",
  "mesa_drivers",
  "libGL",
  "libGLU",
  "libglut",
  "libXinerama",
  "libXcursor",
  "libXfixes",
  "libXi"
]
