[phases.setup]
nixPkgs = [
    "pkgs.libglvnd",
    "pkgs.zlib",
    "pkgs.python3",
    "pkgs.libGL",
    "pkgs.libX11",
    "pkgs.libXext",
    "pkgs.libXrender",
    "pkgs.libXrandr",
    "pkgs.mesa"
]
